/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	argoschedulerv1 "github.com/llimon/argo-scheduler/pkg/apis/argoscheduler/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeArgoSchedulers implements ArgoSchedulerInterface
type FakeArgoSchedulers struct {
	Fake *FakeArgoprojV1
	ns   string
}

var argoschedulersResource = schema.GroupVersionResource{Group: "argoproj.io", Version: "v1", Resource: "argoschedulers"}

var argoschedulersKind = schema.GroupVersionKind{Group: "argoproj.io", Version: "v1", Kind: "ArgoScheduler"}

// Get takes name of the argoScheduler, and returns the corresponding argoScheduler object, and an error if there is any.
func (c *FakeArgoSchedulers) Get(name string, options v1.GetOptions) (result *argoschedulerv1.ArgoScheduler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(argoschedulersResource, c.ns, name), &argoschedulerv1.ArgoScheduler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*argoschedulerv1.ArgoScheduler), err
}

// List takes label and field selectors, and returns the list of ArgoSchedulers that match those selectors.
func (c *FakeArgoSchedulers) List(opts v1.ListOptions) (result *argoschedulerv1.ArgoSchedulerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(argoschedulersResource, argoschedulersKind, c.ns, opts), &argoschedulerv1.ArgoSchedulerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &argoschedulerv1.ArgoSchedulerList{ListMeta: obj.(*argoschedulerv1.ArgoSchedulerList).ListMeta}
	for _, item := range obj.(*argoschedulerv1.ArgoSchedulerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested argoSchedulers.
func (c *FakeArgoSchedulers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(argoschedulersResource, c.ns, opts))

}

// Create takes the representation of a argoScheduler and creates it.  Returns the server's representation of the argoScheduler, and an error, if there is any.
func (c *FakeArgoSchedulers) Create(argoScheduler *argoschedulerv1.ArgoScheduler) (result *argoschedulerv1.ArgoScheduler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(argoschedulersResource, c.ns, argoScheduler), &argoschedulerv1.ArgoScheduler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*argoschedulerv1.ArgoScheduler), err
}

// Update takes the representation of a argoScheduler and updates it. Returns the server's representation of the argoScheduler, and an error, if there is any.
func (c *FakeArgoSchedulers) Update(argoScheduler *argoschedulerv1.ArgoScheduler) (result *argoschedulerv1.ArgoScheduler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(argoschedulersResource, c.ns, argoScheduler), &argoschedulerv1.ArgoScheduler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*argoschedulerv1.ArgoScheduler), err
}

// Delete takes name of the argoScheduler and deletes it. Returns an error if one occurs.
func (c *FakeArgoSchedulers) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(argoschedulersResource, c.ns, name), &argoschedulerv1.ArgoScheduler{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeArgoSchedulers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(argoschedulersResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &argoschedulerv1.ArgoSchedulerList{})
	return err
}

// Patch applies the patch and returns the patched argoScheduler.
func (c *FakeArgoSchedulers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *argoschedulerv1.ArgoScheduler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(argoschedulersResource, c.ns, name, pt, data, subresources...), &argoschedulerv1.ArgoScheduler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*argoschedulerv1.ArgoScheduler), err
}
