/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	argoschedulerv1 "github.com/llimon/argo-scheduler/pkg/apis/argoscheduler/v1"
	versioned "github.com/llimon/argo-scheduler/pkg/client/clientset/versioned"
	internalinterfaces "github.com/llimon/argo-scheduler/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/llimon/argo-scheduler/pkg/client/listers/argoscheduler/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ArgoSchedulerInformer provides access to a shared informer and lister for
// ArgoSchedulers.
type ArgoSchedulerInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.ArgoSchedulerLister
}

type argoSchedulerInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewArgoSchedulerInformer constructs a new informer for ArgoScheduler type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewArgoSchedulerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredArgoSchedulerInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredArgoSchedulerInformer constructs a new informer for ArgoScheduler type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredArgoSchedulerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ArgoprojV1().ArgoSchedulers(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ArgoprojV1().ArgoSchedulers(namespace).Watch(options)
			},
		},
		&argoschedulerv1.ArgoScheduler{},
		resyncPeriod,
		indexers,
	)
}

func (f *argoSchedulerInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredArgoSchedulerInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *argoSchedulerInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&argoschedulerv1.ArgoScheduler{}, f.defaultInformer)
}

func (f *argoSchedulerInformer) Lister() v1.ArgoSchedulerLister {
	return v1.NewArgoSchedulerLister(f.Informer().GetIndexer())
}
